// <auto-generated />
using FuscaFilmes.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FuscaFilmes.API.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250717182206_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.18");

            modelBuilder.Entity("FuscaFilmes.API.Entities.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Christopher Nolan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Steven Spielberg"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Quentin Tarantino"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Martin Scorsese"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Greta Gerwig"
                        });
                });

            modelBuilder.Entity("FuscaFilmes.API.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DirectorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReleasedYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DirectorId = 1,
                            ReleasedYear = 2010,
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 2,
                            DirectorId = 1,
                            ReleasedYear = 2014,
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 3,
                            DirectorId = 2,
                            ReleasedYear = 1993,
                            Title = "Jurassic Park"
                        },
                        new
                        {
                            Id = 4,
                            DirectorId = 2,
                            ReleasedYear = 1993,
                            Title = "Schindler's List"
                        },
                        new
                        {
                            Id = 5,
                            DirectorId = 3,
                            ReleasedYear = 1994,
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            Id = 6,
                            DirectorId = 3,
                            ReleasedYear = 2012,
                            Title = "Django Unchained"
                        },
                        new
                        {
                            Id = 7,
                            DirectorId = 4,
                            ReleasedYear = 2013,
                            Title = "The Wolf of Wall Street"
                        },
                        new
                        {
                            Id = 8,
                            DirectorId = 4,
                            ReleasedYear = 1990,
                            Title = "Goodfellas"
                        },
                        new
                        {
                            Id = 9,
                            DirectorId = 5,
                            ReleasedYear = 2017,
                            Title = "Lady Bird"
                        },
                        new
                        {
                            Id = 10,
                            DirectorId = 5,
                            ReleasedYear = 2023,
                            Title = "Barbie"
                        });
                });

            modelBuilder.Entity("FuscaFilmes.API.Entities.Movie", b =>
                {
                    b.HasOne("FuscaFilmes.API.Entities.Director", "Director")
                        .WithMany("Movies")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");
                });

            modelBuilder.Entity("FuscaFilmes.API.Entities.Director", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
