// <auto-generated />
using FuscaFilmes.Repo.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FuscaFilmes.Repo.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250810004527_M2MCreatingCollection")]
    partial class M2MCreatingCollection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.18");

            modelBuilder.Entity("DirectorMovie", b =>
                {
                    b.Property<int>("DirectorsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoviesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DirectorsId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("DirectorMovie");
                });

            modelBuilder.Entity("FuscaFilmes.Domain.Entities.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Christopher Nolan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Steven Spielberg"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Quentin Tarantino"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Martin Scorsese"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Greta Gerwig"
                        });
                });

            modelBuilder.Entity("FuscaFilmes.Domain.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReleasedYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ReleasedYear = 2010,
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 2,
                            ReleasedYear = 2014,
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 3,
                            ReleasedYear = 1993,
                            Title = "Jurassic Park"
                        },
                        new
                        {
                            Id = 4,
                            ReleasedYear = 1993,
                            Title = "Schindler's List"
                        },
                        new
                        {
                            Id = 5,
                            ReleasedYear = 1994,
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            Id = 6,
                            ReleasedYear = 2012,
                            Title = "Django Unchained"
                        },
                        new
                        {
                            Id = 7,
                            ReleasedYear = 2013,
                            Title = "The Wolf of Wall Street"
                        },
                        new
                        {
                            Id = 8,
                            ReleasedYear = 1990,
                            Title = "Goodfellas"
                        },
                        new
                        {
                            Id = 9,
                            ReleasedYear = 2017,
                            Title = "Lady Bird"
                        },
                        new
                        {
                            Id = 10,
                            ReleasedYear = 2023,
                            Title = "Barbie"
                        });
                });

            modelBuilder.Entity("DirectorMovie", b =>
                {
                    b.HasOne("FuscaFilmes.Domain.Entities.Director", null)
                        .WithMany()
                        .HasForeignKey("DirectorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuscaFilmes.Domain.Entities.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
